docker_image:
  default: smartbugs/maian:1c92091
cmd: /run_maian_solidity.sh
cmd_bytecode: /run_maian_bytecode.sh
output_parser: Maian
info: Maian is a tool for automatic detection of buggy Ethereum smart contracts of three different types prodigal, suicidal and greedy.
