docker_image:
  default: smartbugs/maian:8bf16ac
cmd: /run_maian_solidity.sh
cmd_bytecode: /run_maian_bytecode.sh
info: Maian is a tool for automatic detection of buggy Ethereum smart contracts of three different types prodigal, suicidal and greedy.
